from datamuse import datamuse
api = datamuse.Datamuse()
rhymes = api.words(rel_rhy='definition', max=5)
meaning_similar = api.words(ml='definition', sp='*', max=5)
often_describe = api.words(rel_jjb='winter', max=10)
often_describe_detail = api.words(rel_jjb='flower', topics='color', max=10)
often_describe_noun = api.words(rel_jja='beautiful', max=10)
word_trigger = api.words(rel_trg='winter', max=10)
word_left = api.words(lc='run', max=10)
word_right = api.words(rc='run', max=10)
word_fw = api.words(rel_bga='run', max=10)
word_bf = api.words(rel_bgb='run', max=10)
suggestions = api.suggest(s='harry potter')
t = api.suggest(s='winter', max_results=10)
word_synonym = api.words(rel_syn='candid', max=10)
word_antonym = api.words(rel_ant='honest', max=10)
# word_kindof = api.words(rel_spc='house', max=10)
# word_follower = api.words(rel_bga='happy', max=10)
word_predecessor = api.words(rel_bgb='birthday', max=10)
# print(often_describe)
# print(often_describe_detail)
# print(word_trigger)
print(t)
#print(word_right)

